import crypto from 'node:crypto';
import { execFile } from 'node:child_process';
import { promisify } from 'node:util';

const execFileAsync = promisify(execFile);
const sequenceLengths = new Set([10, 20, 40, 60, 80, 100]);

export function parseSequenceLength(value) {
  const sequenceLength = Number(value);
  if (!Number.isInteger(sequenceLength) || !sequenceLengths.has(sequenceLength)) {
    throw new Error('Sequence length must be one of 10, 20, 40, 60, 80, or 100.');
  }
  return sequenceLength;
}

export async function runPrediction({ filePath, originalName, sequenceLength, predictorCommand }) {
  if (predictorCommand) {
    try {
      return await runExternalPredictor({ filePath, sequenceLength, predictorCommand });
    } catch (error) {
      return runDemoPrediction({
        originalName,
        sequenceLength,
        fallbackReason: getPredictorErrorMessage(error)
      });
    }
  }

  return runDemoPrediction({ originalName, sequenceLength });
}

async function runExternalPredictor({ filePath, sequenceLength, predictorCommand }) {
  const [command, ...baseArgs] = splitCommand(predictorCommand);
  if (!command) {
    throw new Error('PYTHON_PREDICTOR is empty.');
  }

  const { stdout } = await execFileAsync(command, [...baseArgs, filePath, String(sequenceLength)], {
    timeout: 1000 * 60 * 10
  });
  const parsed = JSON.parse(stdout.trim());
  const label = String(parsed.label || '').toUpperCase();
  const confidence = Number(parsed.confidence);

  if (!['REAL', 'FAKE'].includes(label) || !Number.isFinite(confidence)) {
    throw new Error('Predictor must return JSON with label REAL/FAKE and numeric confidence.');
  }

  return {
    label,
    confidence: clampConfidence(confidence),
    demoMode: false,
    notes: 'Generated by configured Python predictor.'
  };
}

function runDemoPrediction({ originalName, sequenceLength, fallbackReason }) {
  const hash = crypto.createHash('sha256').update(`${originalName}:${sequenceLength}`).digest();
  const score = hash[0] / 255;
  const confidence = 64 + Math.round((hash[1] / 255) * 310) / 10;

  return {
    label: score > 0.5 ? 'FAKE' : 'REAL',
    confidence: clampConfidence(confidence),
    demoMode: true,
    notes: fallbackReason
      ? `Demo prediction. External predictor unavailable: ${fallbackReason}`
      : 'Demo prediction. Configure PYTHON_PREDICTOR to connect the trained PyTorch model.'
  };
}

function clampConfidence(value) {
  return Math.max(1, Math.min(99.9, Math.round(value * 10) / 10));
}

function splitCommand(commandLine) {
  const matches = commandLine.match(/"([^"]+)"|'([^']+)'|[^\s]+/g) || [];
  return matches.map((part) => part.replace(/^["']|["']$/g, ''));
}

function getPredictorErrorMessage(error) {
  const stdout = error.stdout?.trim();
  if (stdout) {
    try {
      const parsed = JSON.parse(stdout);
      if (parsed.error) {
        return parsed.error;
      }
    } catch {
      return stdout.slice(0, 180);
    }
  }

  return (error.message || 'unknown error').slice(0, 180);
}
